# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

pr: none

variables:
  project: "AnizanHelper/AnizanHelper/AnizanHelper.csproj"
  publishProfile: "$(Build.SourcesDirectory)/AnizanHelper/AnizanHelper/Properties/PublishProfiles/AzurePipelines.pubxm"

stages:
- stage: Build
  jobs:
  - job: BuildPackages
    
    pool:
      vmImage: "windows-latest"

    steps:
    - task: UseDotNet@2
      inputs:
        packageType: "sdk"
        version: "3.1.201"

    - task: DotNetCoreCLI@2
      displayName: "dotnet publish"
      inputs:
        publishWebProjects: false
        command: "publish"
        zipAfterPublish: true
        projects: $(project)
        arguments: "-p:PublishProfile=$(publishProfile) -o $(System.DefaultWorkingDirectory)/publish"
        modifyOutputPath: false

    - publish: publish
      artifact: AnizanHelper
      displayName: 'Publish artifacts'

- stage: Publish
  dependsOn:
  - Build
  condition: succeeded()
  jobs:
  - job: PublishAppPackage
    pool:
      vmImage: "windows-latest"
    steps:
      - checkout: none
      
      - download: current
        artifact: AnizanHelper
        displayName: "Download artifact"

      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: "$(Pipeline.Workspace)/AnizanHelper"
          includeRootFolder: false
          archiveType: "zip"
          archiveFile: "AnizanHelper.zip"
          replaceExistingArchive: true

      - task: CopyFilesOverSSH@0
        inputs:
          sshEndpoint: "Taiha-WebServer-SSH"
          contents: "AnizanHelper*.zip"
          targetFolder: "$(SshPublishTargetDirectoryRoot)/files"
          readyTimeout: "20000"
          failOnEmptySource: true